// Do not edit. This file is machine generated by the Resource DLL Wizard.

library ComDev;

{ITE} {RCFileType} {_exe\Debug\ComDev_DRC.rc}

{$R '_exe\Debug\ComDev_DRC.res' '_exe\Debug\ComDev_DRC.rc'}

{$E ENU}

begin
end.
