// Do not edit. This file is machine generated by the Resource DLL Wizard.

library ProjectManager3;

{ITE} {RCFileType} {_exe\Debug\ProjectManager3_DRC.rc}

{$R '_exe\Debug\ProjectManager3_DRC.res' '_exe\Debug\ProjectManager3_DRC.rc'}

{$E ENU}

begin
end.
