// Do not edit. This file is machine generated by the Resource DLL Wizard.

library VCLControl3;

{ITE} {DFMFileType} {VCLControl\ControForm3.dfm}
{ITE} {DFMFileType} {VCLControl\DlgSetupDate.dfm}
{ITE} {DFMFileType} {VCLControl\ExportToPSK6_V3.dfm}
{ITE} {DFMFileType} {VCLControl\FindDevices.dfm}
{ITE} {DFMFileType} {VCLControl\FormDelay2.dfm}
{ITE} {DFMFileType} {VCLControl\FormDlgDev.dfm}
{ITE} {DFMFileType} {VCLControl\FormDlgSetupProject.dfm}
{ITE} {DFMFileType} {VCLControl\FrameDelayDev.dfm}
{ITE} {DFMFileType} {VCLControl\FrameFindDevs2.dfm}
{ITE} {DFMFileType} {VCLControl\SelectPath.dfm}
{ITE} {DFMFileType} {VCLControl\VCLFrmSeltPar.dfm}
{ITE} {DFMFileType} {VCLControl\VCLDlgClc.dfm}
{ITE} {DFMFileType} {VCLControl\VCLDlgExportCaliper.dfm}
{ITE} {DFMFileType} {VCLControl\VCLDlgExportLAS.dfm}
{ITE} {DFMFileType} {VCLControl\VCLDlgRam.dfm}
{ITE} {DFMFileType} {VCLControl\VCLFrameRangeSelect.dfm}
{ITE} {RCFileType} {_exe\Debug\VCLControl3_DRC.rc}

{$R 'VCLControl\ControForm3.dfm' 'FormControl:TForm(DockIForm)'}
{$R 'VCLControl\DlgSetupDate.dfm' 'FormCalendar:TForm'}
{$R 'VCLControl\ExportToPSK6_V3.dfm' 'FormExportToPSK6_V3:TForm(DockIForm)'}
{$R 'VCLControl\FindDevices.dfm' 'FormFindDev:TForm(DockIForm)'}
{$R 'VCLControl\FormDelay2.dfm' 'DialogDelay:TForm(DialogIForm)'}
{$R 'VCLControl\FormDlgDev.dfm' 'FormCreateDev:TForm'}
{$R 'VCLControl\FormDlgSetupProject.dfm' 'FormSetupProject:TForm(DialogIForm)'}
{$R 'VCLControl\FrameDelayDev.dfm' 'FrameDelayInfo:TFrame'}
{$R 'VCLControl\SelectPath.dfm' 'SelectPathFrm:TFrame'}
{$R 'VCLControl\FrameFindDevs2.dfm' 'FrameFindDev:TFrame'}
{$R 'VCLControl\VCLDlgClc.dfm' 'FormDlgClc:TForm(DialogIForm)'}
{$R 'VCLControl\VCLDlgExportCaliper.dfm' 'FormDlgExportCaliper:TForm(DialogIForm)'}
{$R 'VCLControl\VCLDlgExportLAS.dfm' 'FormExportLASP3:TForm(DialogIForm)'}
{$R 'VCLControl\VCLDlgRam.dfm' 'FormDlgRam:TForm(DialogIForm)'}
{$R 'VCLControl\VCLFrameRangeSelect.dfm' 'FrameRangeSelect:TFrame'}
{$R 'VCLControl\VCLFrmSeltPar.dfm' 'FrameSelectParam:TFrame'}

{$R '_exe\Debug\VCLControl3_DRC.res' '_exe\Debug\VCLControl3_DRC.rc'}

{$E ENU}

begin
end.
