// Do not edit. This file is machine generated by the Resource DLL Wizard.

library VCLData;

{ITE} {DFMFileType} {VCLData\AbstractDlgParams.dfm}
{ITE} {DFMFileType} {VCLData\DialogOpenLas.dfm}
{ITE} {DFMFileType} {VCLData\DlgEditParam.dfm}
{ITE} {DFMFileType} {VCLData\DlgFromToGlu.dfm}
{ITE} {DFMFileType} {VCLData\FormWork.dfm}
{ITE} {DFMFileType} {VCLData\VCLFormShowArray.dfm}
{ITE} {DFMFileType} {VCLData\VCLGraphDataForm.dfm}
{ITE} {DFMFileType} {VCLData\VCLTableDataForm.dfm}
{ITE} {RCFileType} {_exe\Debug\VCLData_DRC.rc}

{$R 'VCLData\AbstractDlgParams.dfm' 'FormParamsAbstract:TForm(DialogIForm)'}
{$R 'VCLData\DialogOpenLas.dfm' 'DlgOpenLAS:TForm'}
{$R 'VCLData\DlgEditParam.dfm' 'FormEditParam:TForm(DialogIForm)'}
{$R 'VCLData\DlgFromToGlu.dfm' 'FormDlgGluFilter:TForm'}
{$R 'VCLData\FormWork.dfm' 'FormWrok:TForm(CustomFontIForm)'}
{$R 'VCLData\VCLFormShowArray.dfm' 'FormShowArray:TForm(DockIForm)'}
{$R 'VCLData\VCLGraphDataForm.dfm' 'GraphDataForm:TForm(CustomFormData)'}
{$R 'VCLData\VCLTableDataForm.dfm' 'TableDataForm:TForm(CustomFormData)'}
{$R '_exe\Debug\VCLData_DRC.res' '_exe\Debug\VCLData_DRC.rc'}

{$E ENU}

begin
end.
