// Do not edit. This file is machine generated by the Resource DLL Wizard.

library VCLDialogs;

{ITE} {DFMFileType} {VCLDialogs\VCLDlgConnectIO.dfm}
{ITE} {DFMFileType} {VCLDialogs\VCLDlgConnectIOCOM.dfm}
{ITE} {DFMFileType} {VCLDialogs\VCLDlgConnectIONET.dfm}
{ITE} {DFMFileType} {VCLDialogs\VCLDlgConnectIOWLAN.dfm}
{ITE} {DFMFileType} {VCLDialogs\VCLDlgDevice.dfm}
{ITE} {DFMFileType} {VCLDialogs\VCLDlgOpenLas.dfm}
{ITE} {DFMFileType} {VCLDialogs\VCLDlgOpenP3XML.dfm}
{ITE} {DFMFileType} {VCLDialogs\VCLDlgOptionSetup.dfm}
{ITE} {DFMFileType} {VCLDialogs\VCLDlgRootDevice.dfm}
{ITE} {DFMFileType} {VCLDialogs\VCLFrameSelectParam.dfm}
{ITE} {DFMFileType} {VCLDialogs\VCLFrameSelectPath.dfm}
{ITE} {DFMFileType} {VCLDialogs\VCLFrameTGamma.dfm}
{ITE} {DFMFileType} {VCLDialogs\VCLJDtypeAlphaClolor.dfm}
{ITE} {DFMFileType} {VCLDialogs\VCLJDtypeClolor.dfm}
{ITE} {DFMFileType} {VCLDialogs\VCLJDTypeTGamma.dfm}
{ITE} {RCFileType} {_exe\Debug\VCLDialogs_DRC.rc}

{$R 'VCLDialogs\VCLDlgConnectIO.dfm' 'FormSetupConnect:TForm'}
{$R 'VCLDialogs\VCLDlgConnectIOCOM.dfm' 'FormSetupCom:TForm(FormSetupConnect)'}
{$R 'VCLDialogs\VCLDlgConnectIONET.dfm' 'FormSetupNet:TForm(FormSetupConnect)'}
{$R 'VCLDialogs\VCLDlgConnectIOWLAN.dfm' 'FormSetupWlan:TForm(FormSetupNet)'}
{$R 'VCLDialogs\VCLDlgDevice.dfm' 'DlgSetupDev:TForm'}
{$R 'VCLDialogs\VCLDlgOpenLas.dfm' 'DlgOpenLASDataSet:TForm(DialogIForm)'}
{$R 'VCLDialogs\VCLDlgOpenP3XML.dfm' 'DlgOpenP3DataSet:TForm(DialogIForm)'}
{$R 'VCLDialogs\VCLDlgOptionSetup.dfm' 'FormOptionSetup:TForm(DialogIForm)'}
{$R 'VCLDialogs\VCLDlgRootDevice.dfm' 'FormSetupRootDevice:TForm(DialogIForm)'}
{$R 'VCLDialogs\VCLFrameSelectParam.dfm' 'FrameSelectParam:TFrame'}
{$R 'VCLDialogs\VCLFrameSelectPath.dfm' 'FrameSelectPath:TFrame'}
{$R 'VCLDialogs\VCLFrameTGamma.dfm' 'FrameGamma:TFrame'}
{$R 'VCLDialogs\VCLJDtypeAlphaClolor.dfm' 'FormSetAlphaColor:TForm(JDTypeForm)'}
{$R 'VCLDialogs\VCLJDtypeClolor.dfm' 'FormSetColor:TForm(JDTypeForm)'}
{$R 'VCLDialogs\VCLJDTypeTGamma.dfm' 'JDTypeFormGamma:TForm(JDTypeForm)'}
{$R '_exe\Debug\VCLDialogs_DRC.res' '_exe\Debug\VCLDialogs_DRC.rc'}

{$E ENU}

begin
end.
