// Do not edit. This file is machine generated by the Resource DLL Wizard.

library WorkProg;

{ITE} {DFMFileType} {MainExe\ExceptionForm.dfm}
{ITE} {DFMFileType} {MainExe\FirstForm.dfm}
{ITE} {DFMFileType} {MainExe\MainForm.dfm}
{ITE} {DFMFileType} {MainExe\PluginSetupForm.dfm}
{ITE} {RCFileType} {_exe\Debug\WorkProg_DRC.rc}

{$R 'MainExe\ExceptionForm.dfm' 'FormExceptions:TForm(DockIForm)'}
{$R 'MainExe\FirstForm.dfm' 'FormSplash:TForm'}
{$R 'MainExe\MainForm.dfm' 'FormMain:TForm'}
{$R 'MainExe\PluginSetupForm.dfm' 'FormPluginSetup:TForm'}
{$R '_exe\Debug\WorkProg_DRC.res' '_exe\Debug\WorkProg_DRC.rc'}

{$E ENU}

begin
end.
