// Do not edit. This file is machine generated by the Resource DLL Wizard.

library WorkProg;

{ITE} {DFMFileType} {ExceptionForm.dfm}
{ITE} {DFMFileType} {FirstForm.dfm}
{ITE} {DFMFileType} {MainForm.dfm}
{ITE} {DFMFileType} {PluginSetupForm.dfm}
{ITE} {RCFileType} {C\XE\Projects\Device2\_exe\Debug\WorkProg_DRC.rc}

{$R 'ExceptionForm.dfm' 'FormExceptions:TForm(DockIForm)'}
{$R 'FirstForm.dfm' 'FormSplash:TForm'}
{$R 'MainForm.dfm' 'FormMain:TForm'}
{$R 'PluginSetupForm.dfm' 'FormPluginSetup:TForm'}
{$R 'C\XE\Projects\Device2\_exe\Debug\WorkProg_DRC.res' 'C\XE\Projects\Device2\_exe\Debug\WorkProg_DRC.rc'}

{$E ENU}

begin
end.
