// Do not edit. This file is machine generated by the Resource DLL Wizard.

library VCLData;

{ITE} {DFMFileType} {AbstractDlgParams.dfm}
{ITE} {DFMFileType} {DialogOpenLas.dfm}
{ITE} {DFMFileType} {DlgEditParam.dfm}
{ITE} {DFMFileType} {DlgFromToGlu.dfm}
{ITE} {DFMFileType} {FormWork.dfm}
{ITE} {DFMFileType} {VCLFormShowArray.dfm}
{ITE} {DFMFileType} {VCLGraphDataForm.dfm}
{ITE} {DFMFileType} {VCLTableDataForm.dfm}
{ITE} {RCFileType} {C\XE\Projects\Device2\_exe\Debug\VCLData_DRC.rc}

{$R 'AbstractDlgParams.dfm' 'FormParamsAbstract:TForm(DialogIForm)'}
{$R 'DialogOpenLas.dfm' 'DlgOpenLAS:TForm'}
{$R 'DlgEditParam.dfm' 'FormEditParam:TForm(DialogIForm)'}
{$R 'DlgFromToGlu.dfm' 'FormDlgGluFilter:TForm'}
{$R 'FormWork.dfm' 'FormWrok:TForm(CustomFontIForm)'}
{$R 'VCLFormShowArray.dfm' 'FormShowArray:TForm(DockIForm)'}
{$R 'VCLGraphDataForm.dfm' 'GraphDataForm:TForm(CustomFormData)'}
{$R 'VCLTableDataForm.dfm' 'TableDataForm:TForm(CustomFormData)'}
{$R 'C\XE\Projects\Device2\_exe\Debug\VCLData_DRC.res' 'C\XE\Projects\Device2\_exe\Debug\VCLData_DRC.rc'}

{$E ENU}

begin
end.
