// Do not edit. This file is machine generated by the Resource DLL Wizard.

library VCLControl3;

{ITE} {DFMFileType} {ControForm3.dfm}
{ITE} {DFMFileType} {DlgSetupDate.dfm}
{ITE} {DFMFileType} {ExportToPSK6_V3.dfm}
{ITE} {DFMFileType} {FindDevices.dfm}
{ITE} {DFMFileType} {FormDelay2.dfm}
{ITE} {DFMFileType} {FormDlgDev.dfm}
{ITE} {DFMFileType} {FormDlgSetupProject.dfm}
{ITE} {DFMFileType} {FrameDelayDev.dfm}
{ITE} {DFMFileType} {FrameFindDevs2.dfm}
{ITE} {DFMFileType} {SelectPath.dfm}
{ITE} {DFMFileType} {VCLDlgClc.dfm}
{ITE} {DFMFileType} {VCLDlgExportCaliper.dfm}
{ITE} {DFMFileType} {VCLDlgExportLAS.dfm}
{ITE} {DFMFileType} {VCLDlgRam.dfm}
{ITE} {DFMFileType} {VCLFrameRangeSelect.dfm}
{ITE} {DFMFileType} {VCLFrmSeltPar.dfm}
{ITE} {RCFileType} {C\XE\Projects\Device2\_exe\Debug\VCLControl3_DRC.rc}

{$R 'ControForm3.dfm' 'FormControl:TForm(DockIForm)'}
{$R 'DlgSetupDate.dfm' 'FormCalendar:TForm'}
{$R 'ExportToPSK6_V3.dfm' 'FormExportToPSK6_V3:TForm(DockIForm)'}
{$R 'FindDevices.dfm' 'FormFindDev:TForm(DockIForm)'}
{$R 'FormDelay2.dfm' 'DialogDelay:TForm(DialogIForm)'}
{$R 'FormDlgDev.dfm' 'FormCreateDev:TForm'}
{$R 'FormDlgSetupProject.dfm' 'FormSetupProject:TForm(DialogIForm)'}
{$R 'FrameDelayDev.dfm' 'FrameDelayInfo:TFrame'}
{$R 'FrameFindDevs2.dfm' 'FrameFindDev:TFrame'}
{$R 'SelectPath.dfm' 'SelectPathFrm:TFrame'}
{$R 'VCLDlgClc.dfm' 'FormDlgClc:TForm(DialogIForm)'}
{$R 'VCLDlgExportCaliper.dfm' 'FormDlgExportCaliper:TForm(DialogIForm)'}
{$R 'VCLDlgExportLAS.dfm' 'FormExportLASP3:TForm(DialogIForm)'}
{$R 'VCLDlgRam.dfm' 'FormDlgRam:TForm(DialogIForm)'}
{$R 'VCLFrameRangeSelect.dfm' 'FrameRangeSelect:TFrame'}
{$R 'VCLFrmSeltPar.dfm' 'FrameSelectParam:TFrame'}
{$R 'C\XE\Projects\Device2\_exe\Debug\VCLControl3_DRC.res' 'C\XE\Projects\Device2\_exe\Debug\VCLControl3_DRC.rc'}

{$E ENU}

begin
end.
