// Do not edit. This file is machine generated by the Resource DLL Wizard.

library ComDev;

{ITE} {RCFileType} {C\XE\Projects\Device2\_exe\Debug\ComDev_DRC.rc}

{$R 'C\XE\Projects\Device2\_exe\Debug\ComDev_DRC.res' 'C\XE\Projects\Device2\_exe\Debug\ComDev_DRC.rc'}

{$E ENU}

begin
end.
