// Do not edit. This file is machine generated by the Resource DLL Wizard.

library VCLDialogs;

{ITE} {DFMFileType} {VCLDlgConnectIO.dfm}
{ITE} {DFMFileType} {VCLDlgConnectIOCOM.dfm}
{ITE} {DFMFileType} {VCLDlgConnectIONET.dfm}
{ITE} {DFMFileType} {VCLDlgConnectIOWLAN.dfm}
{ITE} {DFMFileType} {VCLDlgDevice.dfm}
{ITE} {DFMFileType} {VCLDlgOpenLas.dfm}
{ITE} {DFMFileType} {VCLDlgOpenP3XML.dfm}
{ITE} {DFMFileType} {VCLDlgOptionSetup.dfm}
{ITE} {DFMFileType} {VCLDlgRootDevice.dfm}
{ITE} {DFMFileType} {VCLFrameSelectParam.dfm}
{ITE} {DFMFileType} {VCLFrameSelectPath.dfm}
{ITE} {DFMFileType} {VCLFrameTGamma.dfm}
{ITE} {DFMFileType} {VCLJDtypeAlphaClolor.dfm}
{ITE} {DFMFileType} {VCLJDtypeClolor.dfm}
{ITE} {DFMFileType} {VCLJDTypeTGamma.dfm}
{ITE} {RCFileType} {C\XE\Projects\Device2\_exe\Debug\VCLDialogs_DRC.rc}

{$R 'VCLDlgConnectIO.dfm' 'FormSetupConnect:TForm'}
{$R 'VCLDlgConnectIOCOM.dfm' 'FormSetupCom:TForm(FormSetupConnect)'}
{$R 'VCLDlgConnectIONET.dfm' 'FormSetupNet:TForm(FormSetupConnect)'}
{$R 'VCLDlgConnectIOWLAN.dfm' 'FormSetupWlan:TForm(FormSetupNet)'}
{$R 'VCLDlgDevice.dfm' 'DlgSetupDev:TForm'}
{$R 'VCLDlgOpenLas.dfm' 'DlgOpenLASDataSet:TForm(DialogIForm)'}
{$R 'VCLDlgOpenP3XML.dfm' 'DlgOpenP3DataSet:TForm(DialogIForm)'}
{$R 'VCLDlgOptionSetup.dfm' 'FormOptionSetup:TForm(DialogIForm)'}
{$R 'VCLDlgRootDevice.dfm' 'FormSetupRootDevice:TForm(DialogIForm)'}
{$R 'VCLFrameSelectParam.dfm' 'FrameSelectParam:TFrame'}
{$R 'VCLFrameSelectPath.dfm' 'FrameSelectPath:TFrame'}
{$R 'VCLFrameTGamma.dfm' 'FrameGamma:TFrame'}
{$R 'VCLJDtypeAlphaClolor.dfm' 'FormSetAlphaColor:TForm(JDTypeForm)'}
{$R 'VCLJDtypeClolor.dfm' 'FormSetColor:TForm(JDTypeForm)'}
{$R 'VCLJDTypeTGamma.dfm' 'JDTypeFormGamma:TForm(JDTypeForm)'}
{$R 'C\XE\Projects\Device2\_exe\Debug\VCLDialogs_DRC.res' 'C\XE\Projects\Device2\_exe\Debug\VCLDialogs_DRC.rc'}

{$E ENU}

begin
end.
