// Do not edit. This file is machine generated by the Resource DLL Wizard.

library ProjectManager3;

{ITE} {RCFileType} {C\XE\Projects\Device2\_exe\Debug\ProjectManager3_DRC.rc}

{$R 'C\XE\Projects\Device2\_exe\Debug\ProjectManager3_DRC.res' 'C\XE\Projects\Device2\_exe\Debug\ProjectManager3_DRC.rc'}

{$E ENU}

begin
end.
